baseURL = 'https://ahhmed-j.github.io/Pagina-Hugo/'
languageCode = 'en-us'
title = 'Portafolio Ahhmed'
theme = 'ananke'

[params]
  site_logo = ''
  description = 'Estudiante de Ingeniería en Software — Portafolio personal'
  background_color_class = 'bg-dark-pink'

